// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUaHtdZzP-GP5_yirKbtUeJqgtA0wQc_c',
    appId: '1:678536890595:web:c02cd0d194b464b3ec1dd6',
    messagingSenderId: '678536890595',
    projectId: 'project-ur',
    authDomain: 'project-ur.firebaseapp.com',
    storageBucket: 'project-ur.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx0FZX3Ni0-K0qx1XSaV34jHjhW4d-vKM',
    appId: '1:678536890595:android:867b585f6f6ceaecec1dd6',
    messagingSenderId: '678536890595',
    projectId: 'project-ur',
    storageBucket: 'project-ur.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvDzaZ9o_y7inpL0mEb0Syo7F_bTk9qIc',
    appId: '1:678536890595:ios:9b9ba6a62987feb9ec1dd6',
    messagingSenderId: '678536890595',
    projectId: 'project-ur',
    storageBucket: 'project-ur.firebasestorage.app',
    iosBundleId: 'com.example.meditrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvDzaZ9o_y7inpL0mEb0Syo7F_bTk9qIc',
    appId: '1:678536890595:ios:9b9ba6a62987feb9ec1dd6',
    messagingSenderId: '678536890595',
    projectId: 'project-ur',
    storageBucket: 'project-ur.firebasestorage.app',
    iosBundleId: 'com.example.meditrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUaHtdZzP-GP5_yirKbtUeJqgtA0wQc_c',
    appId: '1:678536890595:web:5cc9a0ad9c23da2aec1dd6',
    messagingSenderId: '678536890595',
    projectId: 'project-ur',
    authDomain: 'project-ur.firebaseapp.com',
    storageBucket: 'project-ur.firebasestorage.app',
  );
}
